name: "Squashing Commits GA"
description: 'Squash last x commits from the history'
inputs:
  no_commits:
    description: 'Number of commits to be squashed'
    required: true
    default: 1
  user_email:
    description: 'User git email needed to interact with git repo'
    required: false
#    default: "tools+github-shpock-ci@shpock.com"
  user_name:
    description: 'User git name needed to interact with git repo'
    required: false
#    default: "shpock-ci"
  target_branch:
    description: "target branch name where the squashing process will take place"
    required: true
  repo_name:
    description: "Git repo name"
    required: false
#    default: "finderly/web"
  github_token:
    description: "Github token"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.no_commits}}
    - ${{ inputs.user_email}}
    - ${{ inputs.user_name}}
    - ${{ inputs.target_branch}}
    - ${{ inputs.repo_name}}
    - ${{ inputs.github_token}}